django_assignement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("project.urls")),
    path('projects', include("project_membership.urls"))
]

project/urls.py
from django.urls import path
from project import views

urlpatterns = [
    path('', views.read_projects, name="create"),
    path('delete-project/<int:id>/', views.delete_project, name="delete_project")
]

project_membership/urls.py
from django.urls import path

from project_membership import views

urlpatterns = [
    path('', views.index, name="memberships-index"),
    path('remove-membership/<int:project_id>/<int:student_id>', views.delete_membership, name="delete-membership")
]

coach/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Coach(User):
    def __str__(self):
        return self.first_name
    pass

project/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from student.models import Student
from coach.models import Coach


# Create your models here.

class Project(models.Model):
    project_name = models.CharField('project title', max_length=30, default='Project name is unset')
    project_duration = models.IntegerField('estimated duration', default=0)
    time_allocated_by_creator = models.IntegerField('Allocated time',
                                                    validators=[MinValueValidator(1), MaxValueValidator(10)])
    needs = models.TextField(max_length=250)
    description = models.TextField(max_length=250)
    validity_state = models.BooleanField(default=False)
    creator = models.OneToOneField(
        Student,
        on_delete=models.CASCADE,
        related_name='project_owner'
    )
    supervisor = models.ForeignKey(
        Coach,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='project_coach'
    )
    members = models.ManyToManyField(
        Student,
        through='project_membership.MembershipInProject',
        related_name='members',
        blank=True
    )

    def split_needs_into_array(self):
        return self.needs.split(',')

project_membership/models.py
from django.db import models
from project.models import Project
from student.models import Student


# Create your models here.
class MembershipInProject(models.Model):
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE
    )
    allocated_time_per_member = models.IntegerField(
        'Allocated time per member'
    )

    def __str__(self):
        return 'Member ' + self.student.first_name

    class Meta:
        unique_together = ("student", "project")

student/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Student(User):
    def __str__(self):
        return self.first_name
    pass

coach/views.py
from django.shortcuts import render

# Create your views here.

project/views.py
from django.shortcuts import render, redirect
from project.models import Project
from . import form


# Create your views here.
def read_projects(request):
    if request.method == 'POST':
        data = form.CreateProject(request.POST)
        if data.is_valid():
            print('data saved successfully')
            data.save()
        else:
            print('there were an error occured...')
            print(data.errors)
        return redirect('create')
    else:
        project_form = form.CreateProject()
        return render(request, 'Project/index.html',
                      {'projects': Project.objects.all(),
                       'form': project_form})


def delete_project(request, id):
    project = Project.objects.filter(id=id)
    project.delete()
    return redirect('create')

project_membership/views.py
from django.shortcuts import render, redirect

from project.models import Project
from project_membership import form
from student.models import Student
from .models import MembershipInProject


# Create your views here.
def index(request):
    projects = Project.objects.all()
    if request.method == 'POST':
        data = form.CreateMembership(request.POST)
        if data.is_valid():
            print('data saved successfully')
            data.save()
        else:
            print('there were an error occured...')
            print(data.errors)
        return redirect('memberships-index')
    else:
        membership_form = form.CreateMembership()
        return render(request, 'Project-membership/index.html', {'projects': projects, 'form': membership_form})


def delete_membership(request, project_id, student_id):
    project = Project.objects.get(id=project_id)
    student = Student.objects.get(id=student_id)
    membership = MembershipInProject.objects.get(project=project, student=student)
    membership.delete()
    return redirect('memberships-index')

student/views.py
from django.shortcuts import render

# Create your views here.

templates/Base/footer.html
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h1 class="title">BLK•</h1>
                </div>
                <div class="col-md-3">
                    <ul class="nav">
                        <li class="nav-item">
                            <a href="./index.html" class="nav-link">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./examples/landing-page.html" class="nav-link">
                                Landing
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./examples/register-page.html" class="nav-link">
                                Register
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="./examples/profile-page.html" class="nav-link">
                                Profile
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <ul class="nav">
                        <li class="nav-item">
                            <a href="https://creative-tim.com/contact-us" class="nav-link">
                                Contact Us
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://creative-tim.com/about-us" class="nav-link">
                                About Us
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://creative-tim.com/blog" class="nav-link">
                                Blog
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://opensource.org/licenses/MIT" class="nav-link">
                                License
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h3 class="title">Follow us:</h3>
                    <div class="btn-wrapper profile">
                        <a target="_blank" href="https://twitter.com/creativetim"
                           class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip"
                           data-original-title="Follow us">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a target="_blank" href="https://www.facebook.com/creativetim"
                           class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip"
                           data-original-title="Like us">
                            <i class="fab fa-facebook-square"></i>
                        </a>
                        <a target="_blank" href="https://dribbble.com/creativetim"
                           class="btn btn-icon btn-neutral  btn-round btn-simple" data-toggle="tooltip"
                           data-original-title="Follow us">
                            <i class="fab fa-dribbble"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/Base/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent " color-on-scroll="100">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="https://demos.creative-tim.com/blk-design-system/index.html" rel="tooltip"
               title="Designed and Coded by Creative Tim" data-placement="bottom" target="_blank">
                <span>Django</span> workshop
            </a>
            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <div class="navbar-collapse-header">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a>
                            BLK•
                        </a>
                    </div>
                    <div class="col-6 collapse-close text-right">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navigation"
                                aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa fa-cogs d-lg-none d-xl-none"></i> Coaches
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa fa-cogs d-lg-none d-xl-none"></i> Students
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'create' %}" class="nav-link">
                        <i class="fa fa-cogs d-lg-none d-xl-none"></i> projects
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'memberships-index' %}" class="nav-link">
                        <i class="fa fa-cogs d-lg-none d-xl-none"></i> Memberships
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/Project-membership/index.html
{% extends 'Base/base.html' %}
{% load static %}
{% block top-page-title %}
    <h1 class="h1-seo animated bounceInUp">Memberships</h1>
    <h3>Manage all the students projects memberships </h3>
{% endblock %}
{% block content %}
    <div class="section section-tabs">
        <div class="container">
            <div class="row">
                {% include 'Project-membership/membership-form.html' %}
                {% for project in projects %}
                    <div class="col-md-6 ml-auto col-xl-6 mr-auto animated slideInRight">
                        <div class="mb-3">
                            <small class="text-uppercase font-weight-bold"></small>
                        </div>
                        <div class="card">
                            <div class="card-header">
                                <h3 style="text-align: center">{{ project.project_name }}</h3>
                            </div>
                            <div class="card-body">
                                <!-- Tab panes -->
                                <div class="tab-content tab-space">
                                    <div class="tab-pane active" id="project{{ project.id }}">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th class="text-center">Student</th>
                                                <th>Role</th>
                                                <th>Allocated time</th>
                                                <th class="text-right">Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for membership in project.membershipinproject_set.all %}
                                                <tr>
                                                    <td class="text-center">{{ membership.student.first_name }} {{ membership.student.last_name }}</td>
                                                    <td>{% if project.creator == membership.student %}
                                                        Creator
                                                    {% else %}
                                                        subscriber
                                                    {% endif %}</td>
                                                    <td>{{ membership.allocated_time_per_member }}</td>
                                                    <td class="td-actions text-right">
                                                        <a rel="tooltip"
                                                           href="{% url 'delete-membership' project_id=project.id student_id=membership.student.id %}"
                                                           class="btn btn-danger btn-sm btn-icon">
                                                            <i class="tim-icons icon-simple-remove"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="ml-auto col-xl-6 mr-auto" style="text-align: center">
                    <button class="btn btn-warning" id="newProjectButton" data-toggle="modal"
                            data-target="#myModal2">Create new membership
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Project-membership/membership-form.html
<!-- Form Modal -->
<div class="modal fade modal-black" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header justify-content-center">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="tim-icons icon-simple-remove text-white"></i>
                </button>
                <div class="text-muted text-center ml-auto mr-auto">
                    <h3 class="mb-0">membership form</h3>
                </div>
            </div>
            <div class="modal-body">
                <form role="form" action="{% url 'memberships-index' %}" method="post">
                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="tim-icons icon-watch-time"></i>
                      </span>
                            </div>
                            {{ form.allocated_time_per_member }}
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="tim-icons icon-atom"></i>
                      </span>
                            </div>
                            {{ form.project }}
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="tim-icons icon-settings"></i>
                      </span>
                            </div>
                            {{ form.student }}
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary my-4">Validate</button>
                    </div>
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>
<!--  End Modal -->

templates/Project/index.html
{% extends 'Base/base.html' %}
{% load static %}
{% block top-page-title %}
    <h1 class="h1-seo animated bounceInUp">Projects section</h1>
    <h3>Manage all your academic projects and keep track with your progress</h3>
{% endblock %}
{% block content %}
    <div class="section section-tabs">
        <div class="container">
            <div class="row">
                {% include 'Project/project-form.html' %}
                {% for project in projects %}
                    {% if forloop.counter|divisibleby:2 %}
                        <div class="col-md-6 ml-auto col-xl-6 mr-auto animated slideInRight">
                    {% else %}
                        <div class="col-md-6 ml-auto col-xl-6 mr-auto animated slideInLeft">
                    {% endif %}
                <div class="mb-3">
                    <small class="text-uppercase font-weight-bold"></small>
                </div>
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-tabs nav-tabs-primary" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#project{{ project.id }}"
                                   role="tablist">
                                    <i class="tim-icons icon-spaceship"></i> Project
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#creator{{ project.id }}" role="tablist">
                                    <i class="tim-icons icon-settings-gear-63"></i> Creator
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#coach{{ project.id }}" role="tablist">
                                    <i class="tim-icons icon-bag-16"></i> Coach
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link "  href="{% url 'delete_project' id=project.id %}" style="background-color: red"
                                   role="tablist">
                                    <i class="tim-icons icon-simple-remove"></i> Delete
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <!-- Tab panes -->
                        <div class="tab-content tab-space">
                            <div class="tab-pane active" id="project{{ project.id }}">
                                <table style="border-collapse:separate;border-spacing:1.5em;">
                                    <tr>
                                        <td style="min-width: 100px"><span
                                                style="color: #00e676;">Name :</span>
                                        </td>
                                        <td>{{ project.project_name }}</td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 100px"><span
                                                style="color: #00e5ff;">Description :</span></td>
                                        <td>{{ project.description }}</td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 150px"><span style="color: #ff8f00;">
                                                Duration  :</span>
                                        </td>
                                        <td><img src="{% static 'img/clock.gif' %}"
                                                 style="max-width: 35px;max-height: 35px;">
                                            &nbsp;{{ project.project_duration }} Minutes
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 150px"><span style="color: #ffeb3b">
                                                Needs  :</span>
                                        </td>
                                        <td>{% for need in project.split_needs_into_array %}
                                            {% if need != "this project needs python 3.8 " %}
                                                <a href="javascript:void(0)"
                                                   class="badge badge-info">{{ need }}&nbsp;</a>
                                            {% endif %}
                                        {% endfor %}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="tab-pane" id="creator{{ project.id }}">
                                <table style="border-collapse:separate;border-spacing:1.5em;">
                                    <tr>
                                        <td style="min-width: 100px"><span
                                                style="color: #00e676;">Full name :</span>
                                        </td>
                                        <td>{{ project.creator.first_name }} {{ project.creator.last_name }}</td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 100px"><span
                                                style="color: #00e5ff;">Email :</span></td>
                                        <td>{{ project.creator.email }}</td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 150px"><span style="color: #ff8f00;">
                                                Username  :</span>
                                        </td>
                                        <td>
                                            {{ project.creator.username }}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="tab-pane" id="coach{{ project.id }}">
                                <table style="border-collapse:separate;border-spacing:1.5em;">
                                    <tr>
                                        <td style="min-width: 100px"><span
                                                style="color: #00e676;">Full name :</span>
                                        </td>
                                        <td>{{ project.supervisor.first_name }} {{ project.supervisor.last_name }}</td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 100px"><span
                                                style="color: #00e5ff;">Email :</span></td>
                                        <td>{{ project.supervisor.email }}</td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 150px"><span style="color: #ff8f00;">
                                                Username  :</span>
                                        </td>
                                        <td>
                                            {{ project.supervisor.username }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="min-width: 150px"><span style="color: #e57373;">
                                                created projects  :</span>
                                        </td>
                                        <td>
                                            {{ project.supervisor.project_coach.count }}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="ml-auto col-xl-6 mr-auto">
                        <button class="btn btn-warning" id="newProjectButton" data-toggle="modal"
                                data-target="#myModal2">Create new project
                        </button>
                    </div>
                </div>

            </div>

        </div>
        {% block extra-js %}
            <script src="{% static 'js/internal/project.js' %}">
        {% endblock %}
{% endblock %}